[outputFormats.PRINT]
baseName = "index"
isHTML = true
mediaType = "text/html"
path = "_print"
permalinkable = false
[params]
rss_sections = ["blog"]
time_format_blog = "Monday, January 02, 2006"
time_format_default = "January 2, 2006"
